<?php 
function createNode($dom, $addTo, $nodeName){
	$createdNode = $dom->createElement($nodeName);
	$createdNode = $addTo->appendChild($createdNode);
	return $createdNode;
}
//load customers from the website
function getDateForFileName(){
	return date('Y_m_d_H_i_s');
}

function addCustomerToIndex($customerId){
	$indexDoc = simplexml_load_file('customer-index.xml');
	$lastValue = $indexDoc->lastIndex;
	$lastValue = $lastValue + 1;
	$dom=new DOMDocument();
	$dom->load("customer-index.xml");
	$value = 	'2290000000'.$lastValue;
	$dom->getElementsByTagName('lastIndex')->item(0)->nodeValue = $lastValue; //update the last value
	//$doc->getElementsByTagName("title")->item(0)->nodeValue = $titleText;
	$customerElement = $dom->createElement('customer');//createNode($dom, $dom->customers,'customer');
	$custIdAttr = $dom->createAttribute('customer_id');
	$custIdVal = $dom->createTextNode($customerId);
	$custIdAttr->appendChild($custIdVal);
	$customerElement->appendChild($custIdAttr);
	$suIdAttr = $dom->createAttribute('cust_sid');
	$suIdVal = $dom->createTextNode($value);
	$suIdAttr->appendChild($suIdVal);
	$customerElement->appendChild($suIdAttr);
	$dom->getElementsByTagName('customers')->item(0)->appendChild($customerElement);
	$dom->save('customer-index.xml');
	return $value;
}


include('connect_magento.php');
$todaysDate = date('Y-m-d\TH:i:s');
$currentDate = date('Y-m-d H:i:s');
$yestDate = date('Y-m-d H:i:s', strtotime($currentDate.' - 1 days'));
$sourceFrom = date('Y-m-d',strtotime($currentDate.' - 1 days'));
$result = $client->call($session, 'customer.list',array(array('created_at' => array('from' => "$sourceFrom"))));
if (isset($result))
{
/*var_dump($result); exit;*/
$domtree = new DOMDocument('1.0', 'UTF-8');
$xmlRoot = $domtree->createElement('DOCUMENT');
$xmlRoot = $domtree->appendChild($xmlRoot);
$customersNode = $domtree->createElement('CUSTOMERS');
$customersNode = $xmlRoot->appendChild($customersNode);
$count =0;
/*while ($customerData = mysql_fetch_array($result))*/
foreach ($result as $customerData) {
	$generatedId = addCustomerToIndex($customerData['customer_id']);
	$customerNode = createNode($domtree, $customersNode, 'CUSTOMER');
	$customerAddsNode = createNode($domtree, $customerNode, 'CUST_ADDRESSS');
	$customerAddNode = createNode($domtree, $customerAddsNode, 'CUST_ADDRESS');
	$customerSupplsNode = createNode($domtree, $customerNode, 'CUST_SUPPLS');	
	for ($i=1; $i <= 20 ; $i++) { 
		$customerSupplNode = createNode($domtree, $customerSupplsNode, 'CUST_SUPPL');
		$udf_no = $domtree->createAttribute('udf_no');
		$customerSupplNode->appendChild($udf_no);
		$udf_noValue = $domtree->createTextNode($i);
		$udf_no->appendChild($udf_noValue);
		$udf_value = $domtree->createAttribute('udf_value');
		$customerSupplNode->appendChild($udf_value);
		$udf_valueValue = $domtree->createTextNode('');
		$udf_value->appendChild($udf_valueValue);
	}
	$customerCardsNode = createNode($domtree, $customerNode, 'CUST_CRDS');
	$customerTermsNode = createNode($domtree, $customerNode, 'CUST_TERMS');


/*Customer Node Attributes Starts here*/
$accept_checks = $domtree->createAttribute('accept_checks');
$customerNode->appendChild($accept_checks);
$active = $domtree->createAttribute('active');
$customerNode->appendChild($active);
$allow_email = $domtree->createAttribute('allow_email');
$customerNode->appendChild($allow_email);
$allow_phone = $domtree->createAttribute('allow_phone');
$customerNode->appendChild($allow_phone);
$allow_post = $domtree->createAttribute('allow_post');
$customerNode->appendChild($allow_post);
$alternate_id1 = $domtree->createAttribute('alternate_id1');
$customerNode->appendChild($alternate_id1);
$alternate_id2 = $domtree->createAttribute('alternate_id2');
$customerNode->appendChild($alternate_id2);
$ar_flag = $domtree->createAttribute('ar_flag');
$customerNode->appendChild($ar_flag);
$cent_payment_amt = $domtree->createAttribute('cent_payment_amt');
$customerNode->appendChild($cent_payment_amt);
$check_limit = $domtree->createAttribute('check_limit');
$customerNode->appendChild($check_limit);
$cms = $domtree->createAttribute('cms');
$customerNode->appendChild($cms);
$cms_post_date = $domtree->createAttribute('cms_post_date');
$customerNode->appendChild($cms_post_date);
$company_name = $domtree->createAttribute('company_name');
$customerNode->appendChild($company_name);
$controller = $domtree->createAttribute('controller');
$customerNode->appendChild($controller);
$created_date = $domtree->createAttribute('created_date');
$customerNode->appendChild($created_date);
$createdby_empl_name = $domtree->createAttribute('createdby_empl_name');
$customerNode->appendChild($createdby_empl_name);
$createdby_sbs_no = $domtree->createAttribute('createdby_sbs_no');
$customerNode->appendChild($createdby_sbs_no);
$credit_limit = $domtree->createAttribute('credit_limit');
$customerNode->appendChild($credit_limit);
$credit_used = $domtree->createAttribute('credit_used');
$customerNode->appendChild($credit_used);
$cust_class_name = $domtree->createAttribute('cust_class_name');
$customerNode->appendChild($cust_class_name);
$cust_id = $domtree->createAttribute('cust_id');
$customerNode->appendChild($cust_id);
$cust_sid = $domtree->createAttribute('cust_sid');
$customerNode->appendChild($cust_sid);
$cust_type = $domtree->createAttribute('cust_type');
$customerNode->appendChild($cust_type);
$detax = $domtree->createAttribute('detax');
$customerNode->appendChild($detax);
$disc_perc_upper_limit = $domtree->createAttribute('disc_perc_upper_limit');
$customerNode->appendChild($disc_perc_upper_limit);
$email_addr = $domtree->createAttribute('email_addr');
$customerNode->appendChild($email_addr);
$first_name = $domtree->createAttribute('first_name');
$customerNode->appendChild($first_name);
$fst_sale_date = $domtree->createAttribute('fst_sale_date');
$customerNode->appendChild($fst_sale_date);
$home_sbs_no = $domtree->createAttribute('home_sbs_no');
$customerNode->appendChild($home_sbs_no);
$home_store_no = $domtree->createAttribute('home_store_no');
$customerNode->appendChild($home_store_no);
$household_code = $domtree->createAttribute('household_code');
$customerNode->appendChild($household_code);
$info1 = $domtree->createAttribute('info1');
$customerNode->appendChild($info1);
$info2 = $domtree->createAttribute('info2');
$customerNode->appendChild($info2);
$last_name = $domtree->createAttribute('last_name');
$customerNode->appendChild($last_name);
$last_sale_date = $domtree->createAttribute('last_sale_date');
$customerNode->appendChild($last_sale_date);
$lst_return_date = $domtree->createAttribute('lst_return_date');
$customerNode->appendChild($lst_return_date);
$lst_sale_amt = $domtree->createAttribute('lst_sale_amt');
$customerNode->appendChild($lst_sale_amt);
$lst_sale_date = $domtree->createAttribute('lst_sale_date');
$customerNode->appendChild($lst_sale_date);
$lty_accumulated = $domtree->createAttribute('lty_accumulated');
$customerNode->appendChild($lty_accumulated);
$lty_balance = $domtree->createAttribute('lty_balance');
$customerNode->appendChild($lty_balance);
$lty_enroll_date = $domtree->createAttribute('lty_enroll_date');
$customerNode->appendChild($lty_enroll_date);
$lty_lvl_locked = $domtree->createAttribute('lty_lvl_locked');
$customerNode->appendChild($lty_lvl_locked);
$lty_lvl_name = $domtree->createAttribute('lty_lvl_name');
$customerNode->appendChild($lty_lvl_name);
$lty_lvl_sid = $domtree->createAttribute('lty_lvl_sid');
$customerNode->appendChild($lty_lvl_sid);
$lty_opt_in = $domtree->createAttribute('lty_opt_in');
$customerNode->appendChild($lty_opt_in);
$lty_opt_in_manual = $domtree->createAttribute('lty_opt_in_manual');
$customerNode->appendChild($lty_opt_in_manual);
$mark1 = $domtree->createAttribute('mark1');
$customerNode->appendChild($mark1);
$mark2 = $domtree->createAttribute('mark2');
$customerNode->appendChild($mark2);
$marketing_flag = $domtree->createAttribute('marketing_flag');
$customerNode->appendChild($marketing_flag);
$max_disc_perc = $domtree->createAttribute('max_disc_perc');
$customerNode->appendChild($max_disc_perc);
$merge_cust_sid = $domtree->createAttribute('merge_cust_sid');
$customerNode->appendChild($merge_cust_sid);
$modified_date = $domtree->createAttribute('modified_date');
$customerNode->appendChild($modified_date);
$modifiedby_empl_name = $domtree->createAttribute('modifiedby_empl_name');
$customerNode->appendChild($modifiedby_empl_name);
$modifiedby_sbs_no = $domtree->createAttribute('modifiedby_sbs_no');
$customerNode->appendChild($modifiedby_sbs_no);
$notes = $domtree->createAttribute('notes');
$customerNode->appendChild($notes);
$orig_controller = $domtree->createAttribute('orig_controller');
$customerNode->appendChild($orig_controller);
$price_lvl = $domtree->createAttribute('price_lvl');
$customerNode->appendChild($price_lvl);
$primary_clerk_name = $domtree->createAttribute('primary_clerk_name');
$customerNode->appendChild($primary_clerk_name);
$primary_clerk_sbs_no = $domtree->createAttribute('primary_clerk_sbs_no');
$customerNode->appendChild($primary_clerk_sbs_no);
$qb_id = $domtree->createAttribute('qb_id');
$customerNode->appendChild($qb_id);
$ref_cust_sid = $domtree->createAttribute('ref_cust_sid');
$customerNode->appendChild($ref_cust_sid);
$region_name = $domtree->createAttribute('region_name');
$customerNode->appendChild($region_name);
$region_sbs_no = $domtree->createAttribute('region_sbs_no');
$customerNode->appendChild($region_sbs_no);
$sbs_no = $domtree->createAttribute('sbs_no');
$customerNode->appendChild($sbs_no);
$sec_lvl = $domtree->createAttribute('sec_lvl');
$customerNode->appendChild($sec_lvl);
$sector_name = $domtree->createAttribute('sector_name');
$customerNode->appendChild($sector_name);
$shipping_priority = $domtree->createAttribute('shipping_priority');
$customerNode->appendChild($shipping_priority);
$station = $domtree->createAttribute('station');
$customerNode->appendChild($station);
$status = $domtree->createAttribute('status');
$customerNode->appendChild($status);
$store_credit = $domtree->createAttribute('store_credit');
$customerNode->appendChild($store_credit);
$store_no = $domtree->createAttribute('store_no');
$customerNode->appendChild($store_no);
$tax_area2_name = $domtree->createAttribute('tax_area2_name');
$customerNode->appendChild($tax_area2_name);
$tax_area_name = $domtree->createAttribute('tax_area_name');
$customerNode->appendChild($tax_area_name);
$term_type = $domtree->createAttribute('term_type');
$customerNode->appendChild($term_type);
$title = $domtree->createAttribute('title');
$customerNode->appendChild($title);
$udf1_date = $domtree->createAttribute('udf1_date');
$customerNode->appendChild($udf1_date);
$udf2_date = $domtree->createAttribute('udf2_date');
$customerNode->appendChild($udf2_date);

//Set default and actual values
$accept_checksValue = $domtree->createTextNode('1');
$accept_checks->appendChild($accept_checksValue);
$activeValue = $domtree->createTextNode('1');
$active->appendChild($activeValue);
$allow_emailValue = $domtree->createTextNode('1');
$allow_email->appendChild($allow_emailValue);
$allow_phoneValue = $domtree->createTextNode('1');
$allow_phone->appendChild($allow_phoneValue);
$allow_postValue = $domtree->createTextNode('0');
$allow_post->appendChild($allow_postValue);
$alternate_id1Value = $domtree->createTextNode('');
$alternate_id1->appendChild($alternate_id1Value);
$alternate_id2Value = $domtree->createTextNode('');
$alternate_id2->appendChild($alternate_id2Value);
$ar_flagValue = $domtree->createTextNode('0');
$ar_flag->appendChild($ar_flagValue);
$cent_payment_amtValue = $domtree->createTextNode('');
$cent_payment_amt->appendChild($cent_payment_amtValue);
$check_limitValue = $domtree->createTextNode('');
$check_limit->appendChild($check_limitValue);
$cmsValue = $domtree->createTextNode('1');
$cms->appendChild($cmsValue);
$cms_post_dateValue = $domtree->createTextNode($todaysDate);
$cms_post_date->appendChild($cms_post_dateValue);
$company_nameValue = $domtree->createTextNode('');
$company_name->appendChild($company_nameValue);
$controllerValue = $domtree->createTextNode('0');
$controller->appendChild($controllerValue);
//'2014-12-24T05:07:24'
$created_dateValue = $domtree->createTextNode(str_replace(' ', 'T', $customerData['created_at']));
$created_date->appendChild($created_dateValue);
$createdby_empl_nameValue = $domtree->createTextNode('SYSADMIN');
$createdby_empl_name->appendChild($createdby_empl_nameValue);
$createdby_sbs_noValue = $domtree->createTextNode('1');
$createdby_sbs_no->appendChild($createdby_sbs_noValue);
$credit_limitValue = $domtree->createTextNode('0');
$credit_limit->appendChild($credit_limitValue);
$credit_usedValue = $domtree->createTextNode('0');
$credit_used->appendChild($credit_usedValue);
$cust_class_nameValue = $domtree->createTextNode('');
$cust_class_name->appendChild($cust_class_nameValue);
$cust_idValue = $domtree->createTextNode($customerData['customer_id']);
$cust_id->appendChild($cust_idValue);
$cust_sidValue = $domtree->createTextNode('-'."$generatedId"); //Change this.
$cust_sid->appendChild($cust_sidValue);
$cust_typeValue = $domtree->createTextNode('0');
$cust_type->appendChild($cust_typeValue);
$detaxValue = $domtree->createTextNode('0');
$detax->appendChild($detaxValue);
$disc_perc_upper_limitValue = $domtree->createTextNode('100');
$disc_perc_upper_limit->appendChild($disc_perc_upper_limitValue);
$email_addrValue = $domtree->createTextNode($customerData['email']);
$email_addr->appendChild($email_addrValue);
$first_nameValue = $domtree->createTextNode($customerData['firstname']);
$first_name->appendChild($first_nameValue);
$fst_sale_dateValue = $domtree->createTextNode('');
$fst_sale_date->appendChild($fst_sale_dateValue);
$home_sbs_noValue = $domtree->createTextNode('1');
$home_sbs_no->appendChild($home_sbs_noValue);
$home_store_noValue = $domtree->createTextNode('0');
$home_store_no->appendChild($home_store_noValue);
$household_codeValue = $domtree->createTextNode('');
$household_code->appendChild($household_codeValue);
$info1Value = $domtree->createTextNode('');
$info1->appendChild($info1Value);
$info2Value = $domtree->createTextNode('');
$info2->appendChild($info2Value);
$last_nameValue = $domtree->createTextNode($customerData['lastname']);
$last_name->appendChild($last_nameValue);
$last_sale_dateValue = $domtree->createTextNode('');
$last_sale_date->appendChild($last_sale_dateValue);
$lst_return_dateValue = $domtree->createTextNode('');
$lst_return_date->appendChild($lst_return_dateValue);
$lst_sale_amtValue = $domtree->createTextNode('');
$lst_sale_amt->appendChild($lst_sale_amtValue);
$lst_sale_dateValue = $domtree->createTextNode('');
$lst_sale_date->appendChild($lst_sale_dateValue);
$lty_accumulatedValue = $domtree->createTextNode('');
$lty_accumulated->appendChild($lty_accumulatedValue);
$lty_balanceValue = $domtree->createTextNode('');
$lty_balance->appendChild($lty_balanceValue);
$lty_enroll_dateValue = $domtree->createTextNode('');
$lty_enroll_date->appendChild($lty_enroll_dateValue);
$lty_lvl_lockedValue = $domtree->createTextNode('');
$lty_lvl_locked->appendChild($lty_lvl_lockedValue);
$lty_lvl_nameValue = $domtree->createTextNode('');
$lty_lvl_name->appendChild($lty_lvl_nameValue);
$lty_lvl_sidValue = $domtree->createTextNode('');
$lty_lvl_sid->appendChild($lty_lvl_sidValue);
$lty_opt_inValue = $domtree->createTextNode('');
$lty_opt_in->appendChild($lty_opt_inValue);
$lty_opt_in_manualValue = $domtree->createTextNode('');
$lty_opt_in_manual->appendChild($lty_opt_in_manualValue);
$mark1Value = $domtree->createTextNode('');
$mark1->appendChild($mark1Value);
$mark2Value = $domtree->createTextNode('');
$mark2->appendChild($mark2Value);
$marketing_flagValue = $domtree->createTextNode('');
$marketing_flag->appendChild($marketing_flagValue);
$max_disc_percValue = $domtree->createTextNode('0');
$max_disc_perc->appendChild($max_disc_percValue);
$merge_cust_sidValue = $domtree->createTextNode('');
$merge_cust_sid->appendChild($merge_cust_sidValue);
$modified_dateValue = $domtree->createTextNode(date("c", strtotime($customerData['updated_at'])));//'2014-12-24T05:07:24-08:00');
$modified_date->appendChild($modified_dateValue);
$modifiedby_empl_nameValue = $domtree->createTextNode('');
$modifiedby_empl_name->appendChild($modifiedby_empl_nameValue);
$modifiedby_sbs_noValue = $domtree->createTextNode('');
$modifiedby_sbs_no->appendChild($modifiedby_sbs_noValue);
$notesValue = $domtree->createTextNode('');
$notes->appendChild($notesValue);
$orig_controllerValue = $domtree->createTextNode('0');
$orig_controller->appendChild($orig_controllerValue);
$price_lvlValue = $domtree->createTextNode('1');
$price_lvl->appendChild($price_lvlValue);
$primary_clerk_nameValue = $domtree->createTextNode('');
$primary_clerk_name->appendChild($primary_clerk_nameValue);
$primary_clerk_sbs_noValue = $domtree->createTextNode('');
$primary_clerk_sbs_no->appendChild($primary_clerk_sbs_noValue);
$qb_idValue = $domtree->createTextNode('');
$qb_id->appendChild($qb_idValue);
$ref_cust_sidValue = $domtree->createTextNode('');
$ref_cust_sid->appendChild($ref_cust_sidValue);
$region_nameValue = $domtree->createTextNode('');
$region_name->appendChild($region_nameValue);
$region_sbs_noValue = $domtree->createTextNode('-1');
$region_sbs_no->appendChild($region_sbs_noValue);
$sbs_noValue = $domtree->createTextNode('1');
$sbs_no->appendChild($sbs_noValue);
$sec_lvlValue = $domtree->createTextNode('0');
$sec_lvl->appendChild($sec_lvlValue);
$sector_nameValue = $domtree->createTextNode('');
$sector_name->appendChild($sector_nameValue);
$shipping_priorityValue = $domtree->createTextNode('');
$shipping_priority->appendChild($shipping_priorityValue);
$stationValue = $domtree->createTextNode('');
$station->appendChild($stationValue);
$statusValue = $domtree->createTextNode('0');
$status->appendChild($statusValue);
$store_creditValue = $domtree->createTextNode('0');
$store_credit->appendChild($store_creditValue);
$store_noValue = $domtree->createTextNode('0');
$store_no->appendChild($store_noValue);
$tax_area2_nameValue = $domtree->createTextNode('');
$tax_area2_name->appendChild($tax_area2_nameValue);
$tax_area_nameValue = $domtree->createTextNode('');
$tax_area_name->appendChild($tax_area_nameValue);
$term_typeValue = $domtree->createTextNode('');
$term_type->appendChild($term_typeValue);
$titleValue = $domtree->createTextNode('Mr.');
$title->appendChild($titleValue);
$udf1_dateValue = $domtree->createTextNode('');
$udf1_date->appendChild($udf1_dateValue);
$udf2_dateValue = $domtree->createTextNode('');
$udf2_date->appendChild($udf2_dateValue);
/*Customer Node Attributes Ends here*/

/*Customer Address Attributes Starts here*/
$active = $domtree->createAttribute('active');
$customerAddNode->appendChild($active);
$addr_name = $domtree->createAttribute('addr_name');
$customerAddNode->appendChild($addr_name);
$addr_no = $domtree->createAttribute('addr_no');
$customerAddNode->appendChild($addr_no);
$addr_type = $domtree->createAttribute('addr_type');
$customerAddNode->appendChild($addr_type);
$address1 = $domtree->createAttribute('address1');
$customerAddNode->appendChild($address1);
$address2 = $domtree->createAttribute('address2');
$customerAddNode->appendChild($address2);
$address3 = $domtree->createAttribute('address3');
$customerAddNode->appendChild($address3);
$address4 = $domtree->createAttribute('address4');
$customerAddNode->appendChild($address4);
$address5 = $domtree->createAttribute('address5');
$customerAddNode->appendChild($address5);
$address6 = $domtree->createAttribute('address6');
$customerAddNode->appendChild($address6);
$begin_date = $domtree->createAttribute('begin_date');
$customerAddNode->appendChild($begin_date);
$country_name = $domtree->createAttribute('country_name');
$customerAddNode->appendChild($country_name);
$default_addr = $domtree->createAttribute('default_addr');
$customerAddNode->appendChild($default_addr);
$email_addr = $domtree->createAttribute('email_addr');
$customerAddNode->appendChild($email_addr);
$end_date = $domtree->createAttribute('end_date');
$customerAddNode->appendChild($end_date);
$include_email = $domtree->createAttribute('include_email');
$customerAddNode->appendChild($include_email);
$include_phone = $domtree->createAttribute('include_phone');
$customerAddNode->appendChild($include_phone);
$include_post = $domtree->createAttribute('include_post');
$customerAddNode->appendChild($include_post);
$phone1 = $domtree->createAttribute('phone1');
$customerAddNode->appendChild($phone1);
$phone1_type_name = $domtree->createAttribute('phone1_type_name');
$customerAddNode->appendChild($phone1_type_name);
$phone2 = $domtree->createAttribute('phone2');
$customerAddNode->appendChild($phone2);
$phone2_type_name = $domtree->createAttribute('phone2_type_name');
$customerAddNode->appendChild($phone2_type_name);
$season_end_date = $domtree->createAttribute('season_end_date');
$customerAddNode->appendChild($season_end_date);
$season_start_date = $domtree->createAttribute('season_start_date');
$customerAddNode->appendChild($season_start_date);
$shipping = $domtree->createAttribute('shipping');
$customerAddNode->appendChild($shipping);
$tax_area2_name = $domtree->createAttribute('tax_area2_name');
$customerAddNode->appendChild($tax_area2_name);
$tax_area_name = $domtree->createAttribute('tax_area_name');
$customerAddNode->appendChild($tax_area_name);
$zip = $domtree->createAttribute('zip');
$customerAddNode->appendChild($zip);
//Set default and actual values
$activeValue = $domtree->createTextNode('1');
$active->appendChild($activeValue);
$addr_nameValue = $domtree->createTextNode('');
$addr_name->appendChild($addr_nameValue);
$addr_noValue = $domtree->createTextNode('1');
$addr_no->appendChild($addr_noValue);
$addr_typeValue = $domtree->createTextNode('');
$addr_type->appendChild($addr_typeValue);
$address1Value = $domtree->createTextNode('');
$address1->appendChild($address1Value);
$address2Value = $domtree->createTextNode('');
$address2->appendChild($address2Value);
$address3Value = $domtree->createTextNode('');
$address3->appendChild($address3Value);
$address4Value = $domtree->createTextNode('');
$address4->appendChild($address4Value);
$address5Value = $domtree->createTextNode('');
$address5->appendChild($address5Value);
$address6Value = $domtree->createTextNode('');
$address6->appendChild($address6Value);
$begin_dateValue = $domtree->createTextNode('2014-12-24T05:07:24');
$begin_date->appendChild($begin_dateValue);
$country_nameValue = $domtree->createTextNode('');
$country_name->appendChild($country_nameValue);
$default_addrValue = $domtree->createTextNode('0');
$default_addr->appendChild($default_addrValue);
$email_addrValue = $domtree->createTextNode('');
$email_addr->appendChild($email_addrValue);
$end_dateValue = $domtree->createTextNode('2014-12-24T05:07:24');
$end_date->appendChild($end_dateValue);
$include_emailValue = $domtree->createTextNode('0');
$include_email->appendChild($include_emailValue);
$include_phoneValue = $domtree->createTextNode('0');
$include_phone->appendChild($include_phoneValue);
$include_postValue = $domtree->createTextNode('0');
$include_post->appendChild($include_postValue);
$phone1Value = $domtree->createTextNode('01-12345678');
$phone1->appendChild($phone1Value);
$phone1_type_nameValue = $domtree->createTextNode('');
$phone1_type_name->appendChild($phone1_type_nameValue);
$phone2Value = $domtree->createTextNode('');
$phone2->appendChild($phone2Value);
$phone2_type_nameValue = $domtree->createTextNode('');
$phone2_type_name->appendChild($phone2_type_nameValue);
$season_end_dateValue = $domtree->createTextNode('');
$season_end_date->appendChild($season_end_dateValue);
$season_start_dateValue = $domtree->createTextNode('');
$season_start_date->appendChild($season_start_dateValue);
$shippingValue = $domtree->createTextNode('0');
$shipping->appendChild($shippingValue);
$tax_area2_nameValue = $domtree->createTextNode('');
$tax_area2_name->appendChild($tax_area2_nameValue);
$tax_area_nameValue = $domtree->createTextNode('');
$tax_area_name->appendChild($tax_area_nameValue);
$zipValue = $domtree->createTextNode('');
$zip->appendChild($zipValue);
/*Customer Address Attributes Ends here*/	


      $count++;
}
// save tree to file
$domString = $domtree->save("customers/customerfile_".getDateForFileName().".xml");
logMessage($count." customers added to the file");
} else logMessage('No new customers');
?>