<?php
set_time_limit(0);
function createNode($dom, $addTo, $nodeName){
	$createdNode = $dom->createElement($nodeName);
	$createdNode = $addTo->appendChild($createdNode);
	return $createdNode;
}

function generateSuId(){
	$indexDoc = simplexml_load_file('su-index.xml');
	$lastValue = $indexDoc->lastIndex;
	$lastValue = $lastValue + 1;
	$dom=new DOMDocument();
	$dom->load("su-index.xml");
	$value = 	'2300000000'.$lastValue;
	$dom->getElementsByTagName('lastIndex')->item(0)->nodeValue = $lastValue; 
	$dom->save('su-index.xml');
	return $value;
}

function getCustomerSuId($customerId){
	$indexDoc = simplexml_load_file('customer-index.xml');
	foreach ($indexDoc->customers->customer as $customer) {
		if (strcasecmp($customer['customer_id'], $customerId) == 0)
			return '-'.$customer['cust_sid'];
	}	
}

function formatDate($soureDate){
	return date('Y-m-d\TH:i:s',strtotime("$soureDate"));
}

function getDateForFileName(){
	return date('Y_m_d_H_i_s');
}

//load sales order from the website
include('connect_magento.php');
$todaysDate = date('Y-m-d H:i:s'); //2011-04-21 02:13:00 echo date('Y-m-d', strtotime($Date. ' + 1 days'));
$yestDate = date('Y-m-d', strtotime($todaysDate.' - 1 days'));
//get all orders between ystrday and today
$result = $client->call($session,'order.list',array(array('status'=>'pending'),array('created_at' => array('from' => "$yestDate"))));
if (isset($result))
{
	$domtree = new DOMDocument('1.0', 'UTF-8');
	$xmlRoot = $domtree->createElement('DOCUMENT');
	$xmlRoot = $domtree->appendChild($xmlRoot);
	$sosNode = $domtree->createElement('SOS');
	$sosNode = $xmlRoot->appendChild($sosNode);
	$count =0;
	foreach ($result as $salesOrder) {
		++$count;
		$saleOrderInfo = $client->call($session, 'sales_order.info', $salesOrder['increment_id']);
			$soNode = createNode($domtree, $sosNode, 'SO');
			$active = $domtree->createAttribute('active');
			$soNode->appendChild($active);
			$activeValue = $domtree->createTextNode('1');
			$active->appendChild($activeValue);
			$activity_perc = $domtree->createAttribute('activity_perc');
			$soNode->appendChild($activity_perc);
			$activity_percValue = $domtree->createTextNode('100');
			$activity_perc->appendChild($activity_percValue);
			$activity_perc2 = $domtree->createAttribute('activity_perc2');
			$soNode->appendChild($activity_perc2);
			$activity_perc2Value = $domtree->createTextNode('');
			$activity_perc2->appendChild($activity_perc2Value);
			$activity_perc3 = $domtree->createAttribute('activity_perc3');
			$soNode->appendChild($activity_perc3);
			$activity_perc3Value = $domtree->createTextNode('');
			$activity_perc3->appendChild($activity_perc3Value);
			$activity_perc4 = $domtree->createAttribute('activity_perc4');
			$soNode->appendChild($activity_perc4);
			$activity_perc4Value = $domtree->createTextNode('');
			$activity_perc4->appendChild($activity_perc4Value);
			$activity_perc5 = $domtree->createAttribute('activity_perc5');
			$soNode->appendChild($activity_perc5);
			$activity_perc5Value = $domtree->createTextNode('');
			$activity_perc5->appendChild($activity_perc5Value);
			$addr_no = $domtree->createAttribute('addr_no');
			$soNode->appendChild($addr_no);
			$addr_noValue = $domtree->createTextNode('1');
			$addr_no->appendChild($addr_noValue);
			$cancel_date = $domtree->createAttribute('cancel_date');
			$soNode->appendChild($cancel_date);
			$cancel_dateValue = $domtree->createTextNode('');
			$cancel_date->appendChild($cancel_dateValue);
			$clerk_name = $domtree->createAttribute('clerk_name');
			$soNode->appendChild($clerk_name);
			$clerk_nameValue = $domtree->createTextNode('SYSADMIN');
			$clerk_name->appendChild($clerk_nameValue);
			$clerk_name2 = $domtree->createAttribute('clerk_name2');
			$soNode->appendChild($clerk_name2);
			$clerk_name2Value = $domtree->createTextNode('');
			$clerk_name2->appendChild($clerk_name2Value);
			$clerk_name3 = $domtree->createAttribute('clerk_name3');
			$soNode->appendChild($clerk_name3);
			$clerk_name3Value = $domtree->createTextNode('');
			$clerk_name3->appendChild($clerk_name3Value);
			$clerk_name4 = $domtree->createAttribute('clerk_name4');
			$soNode->appendChild($clerk_name4);
			$clerk_name4Value = $domtree->createTextNode('');
			$clerk_name4->appendChild($clerk_name4Value);
			$clerk_name5 = $domtree->createAttribute('clerk_name5');
			$soNode->appendChild($clerk_name5);
			$clerk_name5Value = $domtree->createTextNode('');
			$clerk_name5->appendChild($clerk_name5Value);
			$clerk_sbs_no = $domtree->createAttribute('clerk_sbs_no');
			$soNode->appendChild($clerk_sbs_no);
			$clerk_sbs_noValue = $domtree->createTextNode('1');
			$clerk_sbs_no->appendChild($clerk_sbs_noValue);
			$clerk_sbs_no2 = $domtree->createAttribute('clerk_sbs_no2');
			$soNode->appendChild($clerk_sbs_no2);
			$clerk_sbs_no2Value = $domtree->createTextNode('');
			$clerk_sbs_no2->appendChild($clerk_sbs_no2Value);
			$clerk_sbs_no3 = $domtree->createAttribute('clerk_sbs_no3');
			$soNode->appendChild($clerk_sbs_no3);
			$clerk_sbs_no3Value = $domtree->createTextNode('');
			$clerk_sbs_no3->appendChild($clerk_sbs_no3Value);
			$clerk_sbs_no4 = $domtree->createAttribute('clerk_sbs_no4');
			$soNode->appendChild($clerk_sbs_no4);
			$clerk_sbs_no4Value = $domtree->createTextNode('');
			$clerk_sbs_no4->appendChild($clerk_sbs_no4Value);
			$clerk_sbs_no5 = $domtree->createAttribute('clerk_sbs_no5');
			$soNode->appendChild($clerk_sbs_no5);
			$clerk_sbs_no5Value = $domtree->createTextNode('');
			$clerk_sbs_no5->appendChild($clerk_sbs_no5Value);
			$cms = $domtree->createAttribute('cms');
			$soNode->appendChild($cms);
			$cmsValue = $domtree->createTextNode('1');
			$cms->appendChild($cmsValue);
			$cms_post_date = $domtree->createAttribute('cms_post_date');
			$soNode->appendChild($cms_post_date);
			$cms_post_dateValue = $domtree->createTextNode('2015-01-09T15:15:09');
			$cms_post_date->appendChild($cms_post_dateValue);
			$controller = $domtree->createAttribute('controller');
			$soNode->appendChild($controller);
			$controllerValue = $domtree->createTextNode('1');
			$controller->appendChild($controllerValue);
			$created_date = $domtree->createAttribute('created_date');
			$soNode->appendChild($created_date);
			$created_dateValue = $domtree->createTextNode(formatDate($saleOrderInfo['created_at']));
			$created_date->appendChild($created_dateValue);
			$createdby_empl_name = $domtree->createAttribute('createdby_empl_name');
			$soNode->appendChild($createdby_empl_name);
			$createdby_empl_nameValue = $domtree->createTextNode('SYSADMIN');
			$createdby_empl_name->appendChild($createdby_empl_nameValue);
			$createdby_sbs_no = $domtree->createAttribute('createdby_sbs_no');
			$soNode->appendChild($createdby_sbs_no);
			$createdby_sbs_noValue = $domtree->createTextNode('1');
			$createdby_sbs_no->appendChild($createdby_sbs_noValue);
			$cust_po_no = $domtree->createAttribute('cust_po_no');
			$soNode->appendChild($cust_po_no);
			$cust_po_noValue = $domtree->createTextNode('');
			$cust_po_no->appendChild($cust_po_noValue);
			$cust_sid = $domtree->createAttribute('cust_sid');
			$soNode->appendChild($cust_sid);
			$cust_sidValue = $domtree->createTextNode(getCustomerSuId($saleOrderInfo['customer_id']));
			$cust_sid->appendChild($cust_sidValue);
			$detax = $domtree->createAttribute('detax');
			$soNode->appendChild($detax);
			$detaxValue = $domtree->createTextNode('0');
			$detax->appendChild($detaxValue);
			$disc_amt = $domtree->createAttribute('disc_amt');
			$soNode->appendChild($disc_amt);
			$disc_amtValue = $domtree->createTextNode('0');
			$disc_amt->appendChild($disc_amtValue);
			$disc_perc = $domtree->createAttribute('disc_perc');
			$soNode->appendChild($disc_perc);
			$disc_percValue = $domtree->createTextNode('0');
			$disc_perc->appendChild($disc_percValue);
			$disc_perc_spread = $domtree->createAttribute('disc_perc_spread');
			$soNode->appendChild($disc_perc_spread);
			$disc_perc_spreadValue = $domtree->createTextNode('');
			$disc_perc_spread->appendChild($disc_perc_spreadValue);
			$doc_reason_code = $domtree->createAttribute('doc_reason_code');
			$soNode->appendChild($doc_reason_code);
			$doc_reason_codeValue = $domtree->createTextNode('');
			$doc_reason_code->appendChild($doc_reason_codeValue);
			$doc_source = $domtree->createAttribute('doc_source');
			$soNode->appendChild($doc_source);
			$doc_sourceValue = $domtree->createTextNode('0');
			$doc_source->appendChild($doc_sourceValue);
			$elapsed_time = $domtree->createAttribute('elapsed_time');
			$soNode->appendChild($elapsed_time);
			$elapsed_timeValue = $domtree->createTextNode('56');
			$elapsed_time->appendChild($elapsed_timeValue);
			$empl_name = $domtree->createAttribute('empl_name');
			$soNode->appendChild($empl_name);
			$empl_nameValue = $domtree->createTextNode('SYSADMIN');
			$empl_name->appendChild($empl_nameValue);
			$empl_sbs_no = $domtree->createAttribute('empl_sbs_no');
			$soNode->appendChild($empl_sbs_no);
			$empl_sbs_noValue = $domtree->createTextNode('1');
			$empl_sbs_no->appendChild($empl_sbs_noValue);
			$held = $domtree->createAttribute('held');
			$soNode->appendChild($held);
			$heldValue = $domtree->createTextNode('0');
			$held->appendChild($heldValue);
			$line_pos_seq = $domtree->createAttribute('line_pos_seq');
			$soNode->appendChild($line_pos_seq);
			$line_pos_seqValue = $domtree->createTextNode('1');
			$line_pos_seq->appendChild($line_pos_seqValue);
			$modified_date = $domtree->createAttribute('modified_date');
			$soNode->appendChild($modified_date);
			$modified_dateValue = $domtree->createTextNode(formatDate($saleOrderInfo['updated_at']));
			$modified_date->appendChild($modified_dateValue);
			$modifiedby_empl_name = $domtree->createAttribute('modifiedby_empl_name');
			$soNode->appendChild($modifiedby_empl_name);
			$modifiedby_empl_nameValue = $domtree->createTextNode('SYSADMIN');
			$modifiedby_empl_name->appendChild($modifiedby_empl_nameValue);
			$modifiedby_sbs_no = $domtree->createAttribute('modifiedby_sbs_no');
			$soNode->appendChild($modifiedby_sbs_no);
			$modifiedby_sbs_noValue = $domtree->createTextNode('1');
			$modifiedby_sbs_no->appendChild($modifiedby_sbs_noValue);
			$note = $domtree->createAttribute('note');
			$soNode->appendChild($note);
			$noteValue = $domtree->createTextNode('');
			$note->appendChild($noteValue);
			$orig_controller = $domtree->createAttribute('orig_controller');
			$soNode->appendChild($orig_controller);
			$orig_controllerValue = $domtree->createTextNode('1');
			$orig_controller->appendChild($orig_controllerValue);
			$orig_station = $domtree->createAttribute('orig_station');
			$soNode->appendChild($orig_station);
			$orig_stationValue = $domtree->createTextNode('');
			$orig_station->appendChild($orig_stationValue);
			$orig_store_no = $domtree->createAttribute('orig_store_no');
			$soNode->appendChild($orig_store_no);
			$orig_store_noValue = $domtree->createTextNode('0');
			$orig_store_no->appendChild($orig_store_noValue);
			$over_tax_perc = $domtree->createAttribute('over_tax_perc');
			$soNode->appendChild($over_tax_perc);
			$over_tax_percValue = $domtree->createTextNode('');
			$over_tax_perc->appendChild($over_tax_percValue);
			$over_tax_perc2 = $domtree->createAttribute('over_tax_perc2');
			$soNode->appendChild($over_tax_perc2);
			$over_tax_perc2Value = $domtree->createTextNode('');
			$over_tax_perc2->appendChild($over_tax_perc2Value);
			$pkg_no = $domtree->createAttribute('pkg_no');
			$soNode->appendChild($pkg_no);
			$pkg_noValue = $domtree->createTextNode('');
			$pkg_no->appendChild($pkg_noValue);
			$priority = $domtree->createAttribute('priority');
			$soNode->appendChild($priority);
			$priorityValue = $domtree->createTextNode('');
			$priority->appendChild($priorityValue);
			$ref_so_sid = $domtree->createAttribute('ref_so_sid');
			$soNode->appendChild($ref_so_sid);
			$ref_so_sidValue = $domtree->createTextNode('');
			$ref_so_sid->appendChild($ref_so_sidValue);
			$sbs_no = $domtree->createAttribute('sbs_no');
			$soNode->appendChild($sbs_no);
			$sbs_noValue = $domtree->createTextNode('1');
			$sbs_no->appendChild($sbs_noValue);
			$ship_method = $domtree->createAttribute('ship_method');
			$soNode->appendChild($ship_method);
			$ship_methodValue = $domtree->createTextNode('');
			$ship_method->appendChild($ship_methodValue);
			$ship_perc = $domtree->createAttribute('ship_perc');
			$soNode->appendChild($ship_perc);
			$ship_percValue = $domtree->createTextNode('');
			$ship_perc->appendChild($ship_percValue);
			$shipping_date = $domtree->createAttribute('shipping_date');
			$soNode->appendChild($shipping_date);
			$shipping_dateValue = $domtree->createTextNode('');
			$shipping_date->appendChild($shipping_dateValue);
			$shipto_addr_no = $domtree->createAttribute('shipto_addr_no');
			$soNode->appendChild($shipto_addr_no);
			$shipto_addr_noValue = $domtree->createTextNode('');
			$shipto_addr_no->appendChild($shipto_addr_noValue);
			$shipto_cust_sid = $domtree->createAttribute('shipto_cust_sid');
			$soNode->appendChild($shipto_cust_sid);
			$shipto_cust_sidValue = $domtree->createTextNode('');
			$shipto_cust_sid->appendChild($shipto_cust_sidValue);
			$so_doc_no = $domtree->createAttribute('so_doc_no');
			$soNode->appendChild($so_doc_no);
			$so_doc_noValue = $domtree->createTextNode('0000000001');
			$so_doc_no->appendChild($so_doc_noValue);
			$so_no = $domtree->createAttribute('so_no');
			$soNode->appendChild($so_no);
			$so_noValue = $domtree->createTextNode($saleOrderInfo['increment_id']);
			$so_no->appendChild($so_noValue);
			$so_sid = $domtree->createAttribute('so_sid');
			$soNode->appendChild($so_sid);
			$so_sidValue = $domtree->createTextNode('-'.generateSuId());
			$so_sid->appendChild($so_sidValue);
			$so_type = $domtree->createAttribute('so_type');
			$soNode->appendChild($so_type);
			$so_typeValue = $domtree->createTextNode('0');
			$so_type->appendChild($so_typeValue);
			$station = $domtree->createAttribute('station');
			$soNode->appendChild($station);
			$stationValue = $domtree->createTextNode('');
			$station->appendChild($stationValue);
			$status = $domtree->createAttribute('status');
			$soNode->appendChild($status);
			$statusValue = $domtree->createTextNode('2');
			$status->appendChild($statusValue);
			$store_no = $domtree->createAttribute('store_no');
			$soNode->appendChild($store_no);
			$store_noValue = $domtree->createTextNode('0');
			$store_no->appendChild($store_noValue);
			$tax_area2_name = $domtree->createAttribute('tax_area2_name');
			$soNode->appendChild($tax_area2_name);
			$tax_area2_nameValue = $domtree->createTextNode('');
			$tax_area2_name->appendChild($tax_area2_nameValue);
			$tax_area_name = $domtree->createAttribute('tax_area_name');
			$soNode->appendChild($tax_area_name);
			$tax_area_nameValue = $domtree->createTextNode('');
			$tax_area_name->appendChild($tax_area_nameValue);
			$trans_disc_amt = $domtree->createAttribute('trans_disc_amt');
			$soNode->appendChild($trans_disc_amt);
			$trans_disc_amtValue = $domtree->createTextNode('');
			$trans_disc_amt->appendChild($trans_disc_amtValue);
			$trgt_station = $domtree->createAttribute('trgt_station');
			$soNode->appendChild($trgt_station);
			$trgt_stationValue = $domtree->createTextNode('');
			$trgt_station->appendChild($trgt_stationValue);
			$trgt_store_no = $domtree->createAttribute('trgt_store_no');
			$soNode->appendChild($trgt_store_no);
			$trgt_store_noValue = $domtree->createTextNode('0');
			$trgt_store_no->appendChild($trgt_store_noValue);
			$use_vat = $domtree->createAttribute('use_vat');
			$soNode->appendChild($use_vat);
			$use_vatValue = $domtree->createTextNode('0');
			$use_vat->appendChild($use_vatValue);
			$used_disc_amt = $domtree->createAttribute('used_disc_amt');
			$soNode->appendChild($used_disc_amt);
			$used_disc_amtValue = $domtree->createTextNode('');
			$used_disc_amt->appendChild($used_disc_amtValue);
			$used_subtotal = $domtree->createAttribute('used_subtotal');
			$soNode->appendChild($used_subtotal);
			$used_subtotalValue = $domtree->createTextNode('');
			$used_subtotal->appendChild($used_subtotalValue);
			$used_tax = $domtree->createAttribute('used_tax');
			$soNode->appendChild($used_tax);
			$used_taxValue = $domtree->createTextNode('');
			$used_tax->appendChild($used_taxValue);
			$used_trans_disc_amt = $domtree->createAttribute('used_trans_disc_amt');
			$soNode->appendChild($used_trans_disc_amt);
			$used_trans_disc_amtValue = $domtree->createTextNode('');
			$used_trans_disc_amt->appendChild($used_trans_disc_amtValue);
			$verified = $domtree->createAttribute('verified');
			$soNode->appendChild($verified);
			$verifiedValue = $domtree->createTextNode('0');
			$verified->appendChild($verifiedValue);
			$web_so_type = $domtree->createAttribute('web_so_type');
			$soNode->appendChild($web_so_type);
			$web_so_typeValue = $domtree->createTextNode('0');
			$web_so_type->appendChild($web_so_typeValue);
			$fullAddress = $saleOrderInfo['shipping_address']['street'].' '.$saleOrderInfo['shipping_address']['city'];
			$addressSplit = null;
			if (strlen($fullAddress) > 30){
				$addressSplit = str_split($fullAddress,strlen($fullAddress)/3);				
			}
			$customerNode = createNode($domtree, $soNode, 'CUSTOMER');
			$address1 = $domtree->createAttribute('address1');
			$customerNode->appendChild($address1);
			$val = isset($addressSplit[0]) ? $addressSplit[0] : '';
			$address1Value = $domtree->createTextNode("$val");
			$address1->appendChild($address1Value);
			$address2 = $domtree->createAttribute('address2');
			$customerNode->appendChild($address2);
			$val = isset($addressSplit[1]) ? $addressSplit[1] : '';
			$address2Value = $domtree->createTextNode("$val");
			$address2->appendChild($address2Value);
			$address3 = $domtree->createAttribute('address3');
			$customerNode->appendChild($address3);
			$val = isset($addressSplit[2]) ? $addressSplit[2] : '';
			$address3Value = $domtree->createTextNode("$val");
			$address3->appendChild($address3Value);
			$address4 = $domtree->createAttribute('address4');
			$customerNode->appendChild($address4);
			$val = isset($addressSplit[3]) ? $addressSplit[3] : '';
			$address4Value = $domtree->createTextNode("$val");
			$address4->appendChild($address4Value);
			$address5 = $domtree->createAttribute('address5');
			$customerNode->appendChild($address5);
			$address5Value = $domtree->createTextNode('');
			$address5->appendChild($address5Value);
			$address6 = $domtree->createAttribute('address6');
			$customerNode->appendChild($address6);
			$address6Value = $domtree->createTextNode('');
			$address6->appendChild($address6Value);
			$alternate_id1 = $domtree->createAttribute('alternate_id1');
			$customerNode->appendChild($alternate_id1);
			$alternate_id1Value = $domtree->createTextNode('');
			$alternate_id1->appendChild($alternate_id1Value);
			$alternate_id2 = $domtree->createAttribute('alternate_id2');
			$customerNode->appendChild($alternate_id2);
			$alternate_id2Value = $domtree->createTextNode('');
			$alternate_id2->appendChild($alternate_id2Value);
			$cms = $domtree->createAttribute('cms');
			$customerNode->appendChild($cms);
			$cmsValue = $domtree->createTextNode('1');
			$cms->appendChild($cmsValue);
			$company_name = $domtree->createAttribute('company_name');
			$customerNode->appendChild($company_name);
			$company_nameValue = $domtree->createTextNode('');
			$company_name->appendChild($company_nameValue);
			$country_name = $domtree->createAttribute('country_name');
			$customerNode->appendChild($country_name);
			$country_nameValue = $domtree->createTextNode('');
			$country_name->appendChild($country_nameValue);
			$cust_id = $domtree->createAttribute('cust_id');
			$customerNode->appendChild($cust_id);
			$cust_idValue = $domtree->createTextNode($saleOrderInfo['customer_id']);
			$cust_id->appendChild($cust_idValue);
			$cust_sid = $domtree->createAttribute('cust_sid');
			$customerNode->appendChild($cust_sid);

			$cust_sidValue = $domtree->createTextNode(getCustomerSuId($saleOrderInfo['customer_id']));
			$cust_sid->appendChild($cust_sidValue);
			$detax = $domtree->createAttribute('detax');
			$customerNode->appendChild($detax);
			$detaxValue = $domtree->createTextNode('0');
			$detax->appendChild($detaxValue);
			$first_name = $domtree->createAttribute('first_name');
			$customerNode->appendChild($first_name);
			$first_nameValue = $domtree->createTextNode($saleOrderInfo['shipping_address']['firstname']);
			$first_name->appendChild($first_nameValue);
			$info1 = $domtree->createAttribute('info1');
			$customerNode->appendChild($info1);
			$info1Value = $domtree->createTextNode('');
			$info1->appendChild($info1Value);
			$info2 = $domtree->createAttribute('info2');
			$customerNode->appendChild($info2);
			$info2Value = $domtree->createTextNode('');
			$info2->appendChild($info2Value);
			$last_name = $domtree->createAttribute('last_name');
			$customerNode->appendChild($last_name);
			$last_nameValue = $domtree->createTextNode($saleOrderInfo['shipping_address']['lastname']);
			$last_name->appendChild($last_nameValue);
			$modified_date = $domtree->createAttribute('modified_date');
			$customerNode->appendChild($modified_date);
			$modified_dateValue = $domtree->createTextNode(formatDate($saleOrderInfo['updated_at']));
			$modified_date->appendChild($modified_dateValue);
			$phone1 = $domtree->createAttribute('phone1');
			$customerNode->appendChild($phone1);
			$phone1Value = $domtree->createTextNode($saleOrderInfo['shipping_address']['telephone']);
			$phone1->appendChild($phone1Value);
			$phone2 = $domtree->createAttribute('phone2');
			$customerNode->appendChild($phone2);
			$phone2Value = $domtree->createTextNode('');
			$phone2->appendChild($phone2Value);
			$price_lvl = $domtree->createAttribute('price_lvl');
			$customerNode->appendChild($price_lvl);
			$price_lvlValue = $domtree->createTextNode('');
			$price_lvl->appendChild($price_lvlValue);
			$sbs_no = $domtree->createAttribute('sbs_no');
			$customerNode->appendChild($sbs_no);
			$sbs_noValue = $domtree->createTextNode('1');
			$sbs_no->appendChild($sbs_noValue);
			$shipping = $domtree->createAttribute('shipping');
			$customerNode->appendChild($shipping);
			$shippingValue = $domtree->createTextNode('0');
			$shipping->appendChild($shippingValue);
			$station = $domtree->createAttribute('station');
			$customerNode->appendChild($station);
			$stationValue = $domtree->createTextNode('');
			$station->appendChild($stationValue);
			$store_no = $domtree->createAttribute('store_no');
			$customerNode->appendChild($store_no);
			$store_noValue = $domtree->createTextNode('11');
			$store_no->appendChild($store_noValue);
			$tax_area_name = $domtree->createAttribute('tax_area_name');
			$customerNode->appendChild($tax_area_name);
			$tax_area_nameValue = $domtree->createTextNode('');
			$tax_area_name->appendChild($tax_area_nameValue);
			$title = $domtree->createAttribute('title');
			$customerNode->appendChild($title);
			$titleValue = $domtree->createTextNode('');
			$title->appendChild($titleValue);
			$zip = $domtree->createAttribute('zip');
			$customerNode->appendChild($zip);
			$zipValue = $domtree->createTextNode('');
			$zip->appendChild($zipValue);

			$invoiceSuId = generateSuId();

			$shipToNode = createNode($domtree, $soNode, 'SHIPTO_CUSTOMER');
			$soSuppl = createNode($domtree, $soNode, 'SO_SUPPLS');
			$soComments = createNode($domtree, $soNode, 'SO_COMMENTS');
			$soInstrs = createNode($domtree, $soNode, 'SO_INSTRS');
			$soFees = createNode($domtree, $soNode, 'SO_FEES');
			$soTenders = createNode($domtree, $soNode, 'SO_TENDERS');
			$soDepsts = createNode($domtree, $soNode, 'SO_DEPSTS');
			$soDepst = createNode($domtree, $soDepsts, 'SO_DEPST');

			$created_date = $domtree->createAttribute('created_date');
			$soDepst->appendChild($created_date);
			$created_dateValue = $domtree->createTextNode(formatDate($saleOrderInfo['created_at']));
			$created_date->appendChild($created_dateValue);
			$depst_used = $domtree->createAttribute('depst_used');
			$soDepst->appendChild($depst_used);
			$depst_usedValue = $domtree->createTextNode('0');
			$depst_used->appendChild($depst_usedValue);
			$invc_sid = $domtree->createAttribute('invc_sid');
			$soDepst->appendChild($invc_sid);
			$invc_sidValue = $domtree->createTextNode('-'."$invoiceSuId");
			$invc_sid->appendChild($invc_sidValue);

			$soHists = createNode($domtree, $soNode, 'SO_HISTS');
			$soHist = createNode($domtree, $soHists, 'SO_HIST');

			$created_date = $domtree->createAttribute('created_date');
			$soHist->appendChild($created_date);
			$created_dateValue = $domtree->createTextNode(formatDate($saleOrderInfo['created_at']));
			$created_date->appendChild($created_dateValue);
			$invc_sid = $domtree->createAttribute('invc_sid');
			$soHist->appendChild($invc_sid);
			$invc_sidValue = $domtree->createTextNode('-'."$invoiceSuId");
			$invc_sid->appendChild($invc_sidValue);

			$soItems = createNode($domtree, $soNode, 'SO_ITEMS');
			$itemCount = 0;
			foreach ($saleOrderInfo['items'] as $item) {
				++$itemCount;
				$soItem = createNode($domtree, $soItems, 'SO_ITEM');
				$activity_perc = $domtree->createAttribute('activity_perc');
				$soItem->appendChild($activity_perc);
				$activity_percValue = $domtree->createTextNode('100');
				$activity_perc->appendChild($activity_percValue);
				$activity_perc2 = $domtree->createAttribute('activity_perc2');
				$soItem->appendChild($activity_perc2);
				$activity_perc2Value = $domtree->createTextNode('');
				$activity_perc2->appendChild($activity_perc2Value);
				$activity_perc3 = $domtree->createAttribute('activity_perc3');
				$soItem->appendChild($activity_perc3);
				$activity_perc3Value = $domtree->createTextNode('');
				$activity_perc3->appendChild($activity_perc3Value);
				$activity_perc4 = $domtree->createAttribute('activity_perc4');
				$soItem->appendChild($activity_perc4);
				$activity_perc4Value = $domtree->createTextNode('');
				$activity_perc4->appendChild($activity_perc4Value);
				$activity_perc5 = $domtree->createAttribute('activity_perc5');
				$soItem->appendChild($activity_perc5);
				$activity_perc5Value = $domtree->createTextNode('');
				$activity_perc5->appendChild($activity_perc5Value);
				$alt_alu = $domtree->createAttribute('alt_alu');
				$soItem->appendChild($alt_alu);
				$alt_aluValue = $domtree->createTextNode('');
				$alt_alu->appendChild($alt_aluValue);
				$alt_cost = $domtree->createAttribute('alt_cost');
				$soItem->appendChild($alt_cost);
				$alt_costValue = $domtree->createTextNode('');
				$alt_cost->appendChild($alt_costValue);
				$alt_upc = $domtree->createAttribute('alt_upc');
				$soItem->appendChild($alt_upc);
				$alt_upcValue = $domtree->createTextNode('');
				$alt_upc->appendChild($alt_upcValue);
				$alt_vend_code = $domtree->createAttribute('alt_vend_code');
				$soItem->appendChild($alt_vend_code);
				$alt_vend_codeValue = $domtree->createTextNode('');
				$alt_vend_code->appendChild($alt_vend_codeValue);
				$comm_code = $domtree->createAttribute('comm_code');
				$soItem->appendChild($comm_code);
				$comm_codeValue = $domtree->createTextNode('');
				$comm_code->appendChild($comm_codeValue);
				$cost = $domtree->createAttribute('cost');
				$soItem->appendChild($cost);
				$costValue = $domtree->createTextNode($item['price']);
				$cost->appendChild($costValue);
				$detax = $domtree->createAttribute('detax');
				$soItem->appendChild($detax);
				$detaxValue = $domtree->createTextNode('0');
				$detax->appendChild($detaxValue);
				$disc_reason_name = $domtree->createAttribute('disc_reason_name');
				$soItem->appendChild($disc_reason_name);
				$disc_reason_nameValue = $domtree->createTextNode('');
				$disc_reason_name->appendChild($disc_reason_nameValue);
				$empl_name = $domtree->createAttribute('empl_name');
				$soItem->appendChild($empl_name);
				$empl_nameValue = $domtree->createTextNode('SYSADMIN');
				$empl_name->appendChild($empl_nameValue);
				$empl_name2 = $domtree->createAttribute('empl_name2');
				$soItem->appendChild($empl_name2);
				$empl_name2Value = $domtree->createTextNode('');
				$empl_name2->appendChild($empl_name2Value);
				$empl_name3 = $domtree->createAttribute('empl_name3');
				$soItem->appendChild($empl_name3);
				$empl_name3Value = $domtree->createTextNode('');
				$empl_name3->appendChild($empl_name3Value);
				$empl_name4 = $domtree->createAttribute('empl_name4');
				$soItem->appendChild($empl_name4);
				$empl_name4Value = $domtree->createTextNode('');
				$empl_name4->appendChild($empl_name4Value);
				$empl_name5 = $domtree->createAttribute('empl_name5');
				$soItem->appendChild($empl_name5);
				$empl_name5Value = $domtree->createTextNode('');
				$empl_name5->appendChild($empl_name5Value);
				$empl_sbs_no = $domtree->createAttribute('empl_sbs_no');
				$soItem->appendChild($empl_sbs_no);
				$empl_sbs_noValue = $domtree->createTextNode('1');
				$empl_sbs_no->appendChild($empl_sbs_noValue);
				$empl_sbs_no2 = $domtree->createAttribute('empl_sbs_no2');
				$soItem->appendChild($empl_sbs_no2);
				$empl_sbs_no2Value = $domtree->createTextNode('');
				$empl_sbs_no2->appendChild($empl_sbs_no2Value);
				$empl_sbs_no3 = $domtree->createAttribute('empl_sbs_no3');
				$soItem->appendChild($empl_sbs_no3);
				$empl_sbs_no3Value = $domtree->createTextNode('');
				$empl_sbs_no3->appendChild($empl_sbs_no3Value);
				$empl_sbs_no4 = $domtree->createAttribute('empl_sbs_no4');
				$soItem->appendChild($empl_sbs_no4);
				$empl_sbs_no4Value = $domtree->createTextNode('');
				$empl_sbs_no4->appendChild($empl_sbs_no4Value);
				$empl_sbs_no5 = $domtree->createAttribute('empl_sbs_no5');
				$soItem->appendChild($empl_sbs_no5);
				$empl_sbs_no5Value = $domtree->createTextNode('');
				$empl_sbs_no5->appendChild($empl_sbs_no5Value);
				$force_orig_tax = $domtree->createAttribute('force_orig_tax');
				$soItem->appendChild($force_orig_tax);
				$force_orig_taxValue = $domtree->createTextNode('');
				$force_orig_tax->appendChild($force_orig_taxValue);
				$item_note1 = $domtree->createAttribute('item_note1');
				$soItem->appendChild($item_note1);
				$item_note1Value = $domtree->createTextNode('');
				$item_note1->appendChild($item_note1Value);
				$item_note10 = $domtree->createAttribute('item_note10');
				$soItem->appendChild($item_note10);
				$item_note10Value = $domtree->createTextNode('');
				$item_note10->appendChild($item_note10Value);
				$item_note2 = $domtree->createAttribute('item_note2');
				$soItem->appendChild($item_note2);
				$item_note2Value = $domtree->createTextNode('');
				$item_note2->appendChild($item_note2Value);
				$item_note3 = $domtree->createAttribute('item_note3');
				$soItem->appendChild($item_note3);
				$item_note3Value = $domtree->createTextNode('');
				$item_note3->appendChild($item_note3Value);
				$item_note4 = $domtree->createAttribute('item_note4');
				$soItem->appendChild($item_note4);
				$item_note4Value = $domtree->createTextNode('');
				$item_note4->appendChild($item_note4Value);
				$item_note5 = $domtree->createAttribute('item_note5');
				$soItem->appendChild($item_note5);
				$item_note5Value = $domtree->createTextNode('');
				$item_note5->appendChild($item_note5Value);
				$item_note6 = $domtree->createAttribute('item_note6');
				$soItem->appendChild($item_note6);
				$item_note6Value = $domtree->createTextNode('');
				$item_note6->appendChild($item_note6Value);
				$item_note7 = $domtree->createAttribute('item_note7');
				$soItem->appendChild($item_note7);
				$item_note7Value = $domtree->createTextNode('');
				$item_note7->appendChild($item_note7Value);
				$item_note8 = $domtree->createAttribute('item_note8');
				$soItem->appendChild($item_note8);
				$item_note8Value = $domtree->createTextNode('');
				$item_note8->appendChild($item_note8Value);
				$item_note9 = $domtree->createAttribute('item_note9');
				$soItem->appendChild($item_note9);
				$item_note9Value = $domtree->createTextNode('');
				$item_note9->appendChild($item_note9Value);
				$item_pos = $domtree->createAttribute('item_pos');
				$soItem->appendChild($item_pos);
				$item_posValue = $domtree->createTextNode("$itemCount");
				$item_pos->appendChild($item_posValue);
				$item_sid = $domtree->createAttribute('item_sid');
				$soItem->appendChild($item_sid);
				$item_sidValue = $domtree->createTextNode('-'.$item['sku']);
				$item_sid->appendChild($item_sidValue);
				$kit_flag = $domtree->createAttribute('kit_flag');
				$soItem->appendChild($kit_flag);
				$kit_flagValue = $domtree->createTextNode('0');
				$kit_flag->appendChild($kit_flagValue);
				$lot_number = $domtree->createAttribute('lot_number');
				$soItem->appendChild($lot_number);
				$lot_numberValue = $domtree->createTextNode('');
				$lot_number->appendChild($lot_numberValue);
				$ord_qty = $domtree->createAttribute('ord_qty');
				$soItem->appendChild($ord_qty);
				$ord_qtyValue = $domtree->createTextNode(number_format((float)$item['qty_ordered'], 2, '.', ''));
				$ord_qty->appendChild($ord_qtyValue);
				$orig_cmpnt_item_sid = $domtree->createAttribute('orig_cmpnt_item_sid');
				$soItem->appendChild($orig_cmpnt_item_sid);
				$orig_cmpnt_item_sidValue = $domtree->createTextNode('');
				$orig_cmpnt_item_sid->appendChild($orig_cmpnt_item_sidValue);
				$orig_item_pos = $domtree->createAttribute('orig_item_pos');
				$soItem->appendChild($orig_item_pos);
				$orig_item_posValue = $domtree->createTextNode("$itemCount");
				$orig_item_pos->appendChild($orig_item_posValue);
				$orig_prc_bdt = $domtree->createAttribute('orig_prc_bdt');
				$soItem->appendChild($orig_prc_bdt);
				$orig_prc_bdtValue = $domtree->createTextNode('');
				$orig_prc_bdt->appendChild($orig_prc_bdtValue);
				$orig_price = $domtree->createAttribute('orig_price');
				$soItem->appendChild($orig_price);
				$orig_priceValue = $domtree->createTextNode($item['original_price']);
				$orig_price->appendChild($orig_priceValue);
				$orig_tax_amt = $domtree->createAttribute('orig_tax_amt');
				$soItem->appendChild($orig_tax_amt);
				$orig_tax_amtValue = $domtree->createTextNode($item['tax_amount']);
				$orig_tax_amt->appendChild($orig_tax_amtValue);
				$pkg_item_sid = $domtree->createAttribute('pkg_item_sid');
				$soItem->appendChild($pkg_item_sid);
				$pkg_item_sidValue = $domtree->createTextNode('');
				$pkg_item_sid->appendChild($pkg_item_sidValue);
				$pkg_no = $domtree->createAttribute('pkg_no');
				$soItem->appendChild($pkg_no);
				$pkg_noValue = $domtree->createTextNode('');
				$pkg_no->appendChild($pkg_noValue);
				$pkg_seq_no = $domtree->createAttribute('pkg_seq_no');
				$soItem->appendChild($pkg_seq_no);
				$pkg_seq_noValue = $domtree->createTextNode('');
				$pkg_seq_no->appendChild($pkg_seq_noValue);
				$prc_bdt = $domtree->createAttribute('prc_bdt');
				$soItem->appendChild($prc_bdt);
				$prc_bdtValue = $domtree->createTextNode('');
				$prc_bdt->appendChild($prc_bdtValue);
				$price = $domtree->createAttribute('price');
				$soItem->appendChild($price);
				$priceValue = $domtree->createTextNode($item['price']);
				$price->appendChild($priceValue);
				$price_flag = $domtree->createAttribute('price_flag');
				$soItem->appendChild($price_flag);
				$price_flagValue = $domtree->createTextNode('0');
				$price_flag->appendChild($price_flagValue);
				$price_lvl = $domtree->createAttribute('price_lvl');
				$soItem->appendChild($price_lvl);
				$price_lvlValue = $domtree->createTextNode('1');
				$price_lvl->appendChild($price_lvlValue);
				$promo_flag = $domtree->createAttribute('promo_flag');
				$soItem->appendChild($promo_flag);
				$promo_flagValue = $domtree->createTextNode('0');
				$promo_flag->appendChild($promo_flagValue);
				$scan_upc = $domtree->createAttribute('scan_upc');
				$soItem->appendChild($scan_upc);
				$scan_upcValue = $domtree->createTextNode('');
				$scan_upc->appendChild($scan_upcValue);
				$sched_no = $domtree->createAttribute('sched_no');
				$soItem->appendChild($sched_no);
				$sched_noValue = $domtree->createTextNode('');
				$sched_no->appendChild($sched_noValue);
				$sent_qty = $domtree->createAttribute('sent_qty');
				$soItem->appendChild($sent_qty);
				$sent_qtyValue = $domtree->createTextNode('0');
				$sent_qty->appendChild($sent_qtyValue);
				$serial_no = $domtree->createAttribute('serial_no');
				$soItem->appendChild($serial_no);
				$serial_noValue = $domtree->createTextNode('');
				$serial_no->appendChild($serial_noValue);
				$ship_method = $domtree->createAttribute('ship_method');
				$soItem->appendChild($ship_method);
				$ship_methodValue = $domtree->createTextNode('');
				$ship_method->appendChild($ship_methodValue);
				$shipto_addr_no = $domtree->createAttribute('shipto_addr_no');
				$soItem->appendChild($shipto_addr_no);
				$shipto_addr_noValue = $domtree->createTextNode('');
				$shipto_addr_no->appendChild($shipto_addr_noValue);
				$shipto_cust_sid = $domtree->createAttribute('shipto_cust_sid');
				$soItem->appendChild($shipto_cust_sid);
				$shipto_cust_sidValue = $domtree->createTextNode('');
				$shipto_cust_sid->appendChild($shipto_cust_sidValue);
				$sn_active = $domtree->createAttribute('sn_active');
				$soItem->appendChild($sn_active);
				$sn_activeValue = $domtree->createTextNode('');
				$sn_active->appendChild($sn_activeValue);
				$sn_adjusted = $domtree->createAttribute('sn_adjusted');
				$soItem->appendChild($sn_adjusted);
				$sn_adjustedValue = $domtree->createTextNode('');
				$sn_adjusted->appendChild($sn_adjustedValue);
				$sn_qty = $domtree->createAttribute('sn_qty');
				$soItem->appendChild($sn_qty);
				$sn_qtyValue = $domtree->createTextNode('');
				$sn_qty->appendChild($sn_qtyValue);
				$sn_received = $domtree->createAttribute('sn_received');
				$soItem->appendChild($sn_received);
				$sn_receivedValue = $domtree->createTextNode('');
				$sn_received->appendChild($sn_receivedValue);
				$sn_returned = $domtree->createAttribute('sn_returned');
				$soItem->appendChild($sn_returned);
				$sn_returnedValue = $domtree->createTextNode('');
				$sn_returned->appendChild($sn_returnedValue);
				$sn_returned_to_vnd = $domtree->createAttribute('sn_returned_to_vnd');
				$soItem->appendChild($sn_returned_to_vnd);
				$sn_returned_to_vndValue = $domtree->createTextNode('');
				$sn_returned_to_vnd->appendChild($sn_returned_to_vndValue);
				$sn_so_reserved = $domtree->createAttribute('sn_so_reserved');
				$soItem->appendChild($sn_so_reserved);
				$sn_so_reservedValue = $domtree->createTextNode('');
				$sn_so_reserved->appendChild($sn_so_reservedValue);
				$sn_sold = $domtree->createAttribute('sn_sold');
				$soItem->appendChild($sn_sold);
				$sn_soldValue = $domtree->createTextNode('');
				$sn_sold->appendChild($sn_soldValue);
				$sn_transferred = $domtree->createAttribute('sn_transferred');
				$soItem->appendChild($sn_transferred);
				$sn_transferredValue = $domtree->createTextNode('');
				$sn_transferred->appendChild($sn_transferredValue);
				$spif = $domtree->createAttribute('spif');
				$soItem->appendChild($spif);
				$spifValue = $domtree->createTextNode('');
				$spif->appendChild($spifValue);
				$tax_amt = $domtree->createAttribute('tax_amt');
				$soItem->appendChild($tax_amt);
				$tax_amtValue = $domtree->createTextNode('0');
				$tax_amt->appendChild($tax_amtValue);
				$tax_amt2 = $domtree->createAttribute('tax_amt2');
				$soItem->appendChild($tax_amt2);
				$tax_amt2Value = $domtree->createTextNode('');
				$tax_amt2->appendChild($tax_amt2Value);
				$tax_area2_name = $domtree->createAttribute('tax_area2_name');
				$soItem->appendChild($tax_area2_name);
				$tax_area2_nameValue = $domtree->createTextNode('');
				$tax_area2_name->appendChild($tax_area2_nameValue);
				$tax_code = $domtree->createAttribute('tax_code');
				$soItem->appendChild($tax_code);
				$tax_codeValue = $domtree->createTextNode('-1');
				$tax_code->appendChild($tax_codeValue);
				$tax_code2 = $domtree->createAttribute('tax_code2');
				$soItem->appendChild($tax_code2);
				$tax_code2Value = $domtree->createTextNode('');
				$tax_code2->appendChild($tax_code2Value);
				$tax_perc = $domtree->createAttribute('tax_perc');
				$soItem->appendChild($tax_perc);
				$tax_percValue = $domtree->createTextNode('0');
				$tax_perc->appendChild($tax_percValue);
				$tax_perc2 = $domtree->createAttribute('tax_perc2');
				$soItem->appendChild($tax_perc2);
				$tax_perc2Value = $domtree->createTextNode('');
				$tax_perc2->appendChild($tax_perc2Value);
				$tax_perc_lock = $domtree->createAttribute('tax_perc_lock');
				$soItem->appendChild($tax_perc_lock);
				$tax_perc_lockValue = $domtree->createTextNode('0');
				$tax_perc_lock->appendChild($tax_perc_lockValue);
				$udf_value1 = $domtree->createAttribute('udf_value1');
				$soItem->appendChild($udf_value1);
				$udf_value1Value = $domtree->createTextNode('');
				$udf_value1->appendChild($udf_value1Value);
				$udf_value2 = $domtree->createAttribute('udf_value2');
				$soItem->appendChild($udf_value2);
				$udf_value2Value = $domtree->createTextNode('');
				$udf_value2->appendChild($udf_value2Value);
				$udf_value3 = $domtree->createAttribute('udf_value3');
				$soItem->appendChild($udf_value3);
				$udf_value3Value = $domtree->createTextNode('');
				$udf_value3->appendChild($udf_value3Value);
				$udf_value4 = $domtree->createAttribute('udf_value4');
				$soItem->appendChild($udf_value4);
				$udf_value4Value = $domtree->createTextNode('');
				$udf_value4->appendChild($udf_value4Value);
				$usr_disc_perc = $domtree->createAttribute('usr_disc_perc');
				$soItem->appendChild($usr_disc_perc);
				$usr_disc_percValue = $domtree->createTextNode('0');
				$usr_disc_perc->appendChild($usr_disc_percValue);

				$invnBaseItem = createNode($domtree, $soItem, 'INVN_BASE_ITEM');
				$alu = $domtree->createAttribute('alu');
				$invnBaseItem->appendChild($alu);
				$aluValue = $domtree->createTextNode('');
				$alu->appendChild($aluValue);
				$attr = $domtree->createAttribute('attr');
				$invnBaseItem->appendChild($attr);
				$attrValue = $domtree->createTextNode('RETAIL');
				$attr->appendChild($attrValue);
				$aux1_value = $domtree->createAttribute('aux1_value');
				$invnBaseItem->appendChild($aux1_value);
				$aux1_valueValue = $domtree->createTextNode('');
				$aux1_value->appendChild($aux1_valueValue);
				$aux2_value = $domtree->createAttribute('aux2_value');
				$invnBaseItem->appendChild($aux2_value);
				$aux2_valueValue = $domtree->createTextNode('');
				$aux2_value->appendChild($aux2_valueValue);
				$aux3_value = $domtree->createAttribute('aux3_value');
				$invnBaseItem->appendChild($aux3_value);
				$aux3_valueValue = $domtree->createTextNode('');
				$aux3_value->appendChild($aux3_valueValue);
				$aux4_value = $domtree->createAttribute('aux4_value');
				$invnBaseItem->appendChild($aux4_value);
				$aux4_valueValue = $domtree->createTextNode('');
				$aux4_value->appendChild($aux4_valueValue);
				$aux5_value = $domtree->createAttribute('aux5_value');
				$invnBaseItem->appendChild($aux5_value);
				$aux5_valueValue = $domtree->createTextNode('');
				$aux5_value->appendChild($aux5_valueValue);
				$aux6_value = $domtree->createAttribute('aux6_value');
				$invnBaseItem->appendChild($aux6_value);
				$aux6_valueValue = $domtree->createTextNode('');
				$aux6_value->appendChild($aux6_valueValue);
				$aux7_value = $domtree->createAttribute('aux7_value');
				$invnBaseItem->appendChild($aux7_value);
				$aux7_valueValue = $domtree->createTextNode('');
				$aux7_value->appendChild($aux7_valueValue);
				$aux8_value = $domtree->createAttribute('aux8_value');
				$invnBaseItem->appendChild($aux8_value);
				$aux8_valueValue = $domtree->createTextNode('');
				$aux8_value->appendChild($aux8_valueValue);
				$dcs_code = $domtree->createAttribute('dcs_code');
				$invnBaseItem->appendChild($dcs_code);
				$dcs_codeValue = $domtree->createTextNode('');
				$dcs_code->appendChild($dcs_codeValue);
				$description1 = $domtree->createAttribute('description1');
				$invnBaseItem->appendChild($description1);
				$description1Value = $domtree->createTextNode($item['name']);
				$description1->appendChild($description1Value);
				$description2 = $domtree->createAttribute('description2');
				$invnBaseItem->appendChild($description2);
				$description2Value = $domtree->createTextNode('');
				$description2->appendChild($description2Value);
				$description3 = $domtree->createAttribute('description3');
				$invnBaseItem->appendChild($description3);
				$description3Value = $domtree->createTextNode('');
				$description3->appendChild($description3Value);
				$description4 = $domtree->createAttribute('description4');
				$invnBaseItem->appendChild($description4);
				$description4Value = $domtree->createTextNode('');
				$description4->appendChild($description4Value);
				$ext_flag = $domtree->createAttribute('ext_flag');
				$invnBaseItem->appendChild($ext_flag);
				$ext_flagValue = $domtree->createTextNode('');
				$ext_flag->appendChild($ext_flagValue);
				$flag = $domtree->createAttribute('flag');
				$invnBaseItem->appendChild($flag);
				$flagValue = $domtree->createTextNode('0');
				$flag->appendChild($flagValue);
				$item_no = $domtree->createAttribute('item_no');
				$invnBaseItem->appendChild($item_no);
				$item_noValue = $domtree->createTextNode('8');
				$item_no->appendChild($item_noValue);
				$item_sid = $domtree->createAttribute('item_sid');
				$invnBaseItem->appendChild($item_sid);
				$item_sidValue = $domtree->createTextNode('-'.$item['sku']);
				$item_sid->appendChild($item_sidValue);
				$scale_no = $domtree->createAttribute('scale_no');
				$invnBaseItem->appendChild($scale_no);
				$scale_noValue = $domtree->createTextNode('');
				$scale_no->appendChild($scale_noValue);
				$siz = $domtree->createAttribute('siz');
				$invnBaseItem->appendChild($siz);
				$sizValue = $domtree->createTextNode('');
				$siz->appendChild($sizValue);
				$style_sid = $domtree->createAttribute('style_sid');
				$invnBaseItem->appendChild($style_sid);
				$style_sidValue = $domtree->createTextNode('');
				$style_sid->appendChild($style_sidValue);
				$tax_code = $domtree->createAttribute('tax_code');
				$invnBaseItem->appendChild($tax_code);
				$tax_codeValue = $domtree->createTextNode('-1');
				$tax_code->appendChild($tax_codeValue);
				$udf3_value = $domtree->createAttribute('udf3_value');
				$invnBaseItem->appendChild($udf3_value);
				$udf3_valueValue = $domtree->createTextNode('Inventory');
				$udf3_value->appendChild($udf3_valueValue);
				$udf4_value = $domtree->createAttribute('udf4_value');
				$invnBaseItem->appendChild($udf4_value);
				$udf4_valueValue = $domtree->createTextNode('');
				$udf4_value->appendChild($udf4_valueValue);
				$udf5_value = $domtree->createAttribute('udf5_value');
				$invnBaseItem->appendChild($udf5_value);
				$udf5_valueValue = $domtree->createTextNode('');
				$udf5_value->appendChild($udf5_valueValue);
				$udf6_value = $domtree->createAttribute('udf6_value');
				$invnBaseItem->appendChild($udf6_value);
				$udf6_valueValue = $domtree->createTextNode('');
				$udf6_value->appendChild($udf6_valueValue);
				$upc = $domtree->createAttribute('upc');
				$invnBaseItem->appendChild($upc);
				$upcValue = $domtree->createTextNode($item['product_id']);
				$upc->appendChild($upcValue);
				$use_qty_decimals = $domtree->createAttribute('use_qty_decimals');
				$invnBaseItem->appendChild($use_qty_decimals);
				$use_qty_decimalsValue = $domtree->createTextNode('0');
				$use_qty_decimals->appendChild($use_qty_decimalsValue);
				$vend_code = $domtree->createAttribute('vend_code');
				$invnBaseItem->appendChild($vend_code);
				$vend_codeValue = $domtree->createTextNode('DISTRI');
				$vend_code->appendChild($vend_codeValue);
			}
		

	}
// save tree to file
$domString = $domtree->save("salesorders/saleorderfile_".getDateForFileName().".xml");
logMessage($count." sales order added to the file");
}

?>